# Generated by Django 3.1.4 on 2021-01-14 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0003_auto_20210114_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
